### PR TITLE
Pvs studio warnings

### PR DESCRIPTION
**Pull request by ARMartinelli**
issue #61

### CODE REVIEW

**Comment by mdrocco** [comment]
http://www.di.unito.it/~drocco/pico-pvs-pr66/

Let us try to fix at least the issues about:
- V730: members not initialized in constructors
- V522: potential null-pointer dereferencing

**Comment by ARMartinelli** [comment]
There is a problem with warnings V522. I have fixed that errors putting an assert to check null pointer but pvs-studio still outputs warnings. For an example look at 3a250f9 .
I think that maybe there is a performance problem with the last commit: c0ace20 .
Now the static function "from_string" makes more copies. What do you think about it?

**Comment by mdrocco** [comment]
> There is a problem with warnings V522. I have fixed that errors putting an assert to check null pointer but pvs-studio still outputs warnings. For an example look at [3a250f9](https://github.com/alpha-unito/pico/commit/3a250f91afffafb3cf352ae0cd7bd25f571b7324) .

The problem is that asserts are disabled by the compiler after some level of optimization (sorry, I did not know that at the time the code was written), so the analyzer is right. That can be solved easily by adding some `if`s.

> I think that maybe there is a performance problem with the last commit: [c0ace20](https://github.com/alpha-unito/pico/commit/c0ace205b94eded0d7661991930e1c631c79b878) .
> Now the static function "from_string" makes more copies. What do you think about it?

The easy workaround is to call the default constructor of `key` and `val` upon default construction (as in `std::pair`). PVS-Studio is happy with that.

**Comment by ARMartinelli** [comment]
> The problem is that asserts are disabled by the compiler after some level of optimization (sorry, I did not know that at the time the code was written), so the analyzer is right. That can be solved easily by adding some ifs.

So it's time to solve #23 using exceptions, or you think that for the moment we can write something like:
if (pointer) {
  // use pointer
} 
else
  assert(false) // or exit(1)

**Comment by mdrocco** [comment]
Let us take the simple path here:

```c++
if (pointer) {
  // use pointer
}
else {
  // print something on stderr
  // return some default value if non-void return type
}
```

**Comment by ARMartinelli** [comment]
Done

**Review by mdrocco — APPROVED** [review]

**Comment by mdrocco** [comment]
Almost there :)
- http://www.di.unito.it/~drocco/pico-pvs-pr66/sources/JoinFlatMapByKey.hpp_1.html#ln88
- http://www.di.unito.it/~drocco/pico-pvs-pr66/sources/PEGOptimizations.hpp_2.html#ln111

**Comment by ARMartinelli** [comment]
Done :)

**Review by mdrocco — APPROVED** [review]

**Pull request merged**
